default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: c2s_auth_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: c2s_auth_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: c2s_auth_production
  username: c2s_auth
  password: <%= ENV["C2S_TASK_MANAGEMENT_DATABASE_PASSWORD"] %>
